# Generated by Django 5.1.4 on 2024-12-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mystore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cac_name', models.CharField(max_length=100)),
                ('physicaladdress', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='productimages')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.mystore')),
            ],
        ),
    ]
