# Generated by Django 5.1.4 on 2025-01-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
