# Generated by Django 5.1.4 on 2025-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('cancelled', 'Cancelled'), ('delivery', 'Delivery')], default='Processing', max_length=35),
        ),
    ]
