# Generated by Django 5.1.4 on 2025-01-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myreview',
            name='order',
        ),
    ]
