# Generated by Django 5.1.4 on 2025-01-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_myreview_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
