# Generated by Django 5.1.4 on 2025-01-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.jpeg', null=True, upload_to='profiles'),
        ),
    ]
